list(APPEND PDEKIT_Interpolation_HEADERS
  CellGeoMetric.hpp
  CellFluxMetric.hpp
  PolyCacheCellView.hpp
  CellSolutionMetric.hpp
  FluxSpaceMetric.hpp
  ElementAdaptInterpolator.hpp
  ErrorEstimator.hpp
  FEValues.hpp
  FunctionSpace.hpp
  FunctionSpaceCells.hpp
  FunctionSpaceTraces.hpp
  GeometryCache.hpp
  GeometryCacheBase.hpp
  GeometryMetric.hpp
  L2ProjectionLocal.hpp
  L2ProjectionGlobal.hpp
  MetricFlags.hpp
  CoarseScaleCorrectionOpBuilder.hpp
  ResidualRestrictionLocal.hpp
  mesh_function/ScalarMeshFunctionBase.hpp
  mesh_function/ScalarMeshFunction.hpp
  mesh_function/VectorMeshFunctionBase.hpp
  mesh_function/VectorMeshFunction.hpp
  mesh_function/MeshFunctionSnapshot.hpp
  mesh_function/MeshFunctionTools.hpp
  mesh_function/function_ops/ScalarMeshFunctionUnaryMinusExpr.hpp
  mesh_function/function_ops/ScalarScalarMeshFunctionMultExpr.hpp
  mesh_function/function_ops/ScalarMeshFunctionAddExpr.hpp
  mesh_function/function_ops/ScalarMeshFunctionSubExpr.hpp
  mesh_function/function_ops/VectorMeshFunctionAssign.hpp
  mesh_function/function_ops/ScalarVectorMeshFunctionMultExpr.hpp
  mesh_function/function_ops/VectorMeshFunctionAddExpr.hpp
  mesh_function/function_ops/VectorMeshFunctionSubExpr.hpp
  mesh_function/function_ops/ScalarMeshFVectorMeshFMultExpr.hpp
  mesh_function/function_ops/MeshFunctionNorm.hpp
  mesh_function/ScalarMeshFunctionOps.hpp
  mesh_function/VectorMeshFunctionOps.hpp
  OperatorResidualCellwise.hpp
  OperatorResidualNodal.hpp
  PolyCacheDescription.hpp
  PolyCache.hpp
  PolyMetric.hpp
  SolutionCache.hpp
  SolutionSpaceMetric.hpp
)

list(APPEND PDEKIT_Interpolation_SOURCES
  ElementAdaptInterpolator.cpp
  FEValues.cpp
  L2ProjectionLocal.cpp
  L2ProjectionGlobal.cpp
  ResidualRestrictionLocal.cpp
  PolyCacheDescription.cpp
  PolyCache.cpp
  SolutionCache.cpp
  mesh_function/MeshFunctionTools.cpp
)
