list(APPEND PDEKIT_Mesh_Point_Set_HEADERS
 point_set/StdPointSetBase.hpp
 point_set/DofPointSetLineEquidist.hpp
 point_set/DofPointSetLineWarpblend.hpp
 point_set/DofPointSetTriagEquidist.hpp
 point_set/DofPointSetTriagWarpblend.hpp
 point_set/DofPointSetQuadEquidist.hpp
 point_set/DofPointSetQuadWarpblend.hpp
 point_set/DofPointSetTetraEquidist.hpp
 point_set/DofPointSetTetraWarpblend.hpp
 point_set/DofPointSetHexaEquidist.hpp
 point_set/DofPointSetPyramidEquidist.hpp
 point_set/QdPointSetHexaGauss.hpp
 point_set/QdPointSetLineGauss.hpp
 point_set/QdPointSetLineGaussLobatto.hpp
 point_set/QdPointSetTriagGauss.hpp
 point_set/QdPointSetTriagFaceGauss.hpp
 point_set/QdPointSetQuadGauss.hpp
 point_set/QdPointSetQuadFaceGauss.hpp
 point_set/QdPointSetTetraGauss.hpp
 point_set/QdPointSetTetraFaceGauss.hpp
 point_set/StdPointSetFactory.hpp
 point_set/StdPointSet.hpp
 point_set/QuadraturePermutation.hpp
 point_set/QuadratureTransformUtils.hpp
 point_set/QuadratureAdaptTransformAlgoBase.hpp
 point_set/QuadratureLineAdaptTransformAlgo.hpp
 point_set/QuadratureAdaptTransformAlgoFactory.hpp
)

list(APPEND PDEKIT_Mesh_Point_Set_SOURCES
 point_set/StdPointSetBase.cpp
 point_set/DofPointSetLineEquidist.cpp
 point_set/DofPointSetLineWarpblend.cpp
 point_set/DofPointSetTriagEquidist.cpp
 point_set/DofPointSetTriagWarpblend.cpp
 point_set/DofPointSetQuadEquidist.cpp
 point_set/DofPointSetQuadWarpblend.cpp
 point_set/DofPointSetTetraEquidist.cpp
 point_set/DofPointSetTetraWarpblend.cpp
 point_set/DofPointSetHexaEquidist.cpp
 point_set/DofPointSetPyramidEquidist.cpp
 point_set/QdPointSetHexaGauss.cpp
 point_set/QdPointSetLineGauss.cpp
 point_set/QdPointSetLineGaussLobatto.cpp
 point_set/QdPointSetTriagGauss.cpp
 point_set/QdPointSetTriagFaceGauss.cpp
 point_set/QdPointSetQuadGauss.cpp
 point_set/QdPointSetQuadFaceGauss.cpp
 point_set/QdPointSetTetraGauss.cpp
 point_set/StdPointSetFactory.cpp
 point_set/StdPointSet.cpp
 point_set/QuadraturePermutation.cpp
 point_set/QuadratureTransformUtils.cpp
 point_set/QuadratureAdaptTransformAlgoBase.cpp
 point_set/QuadratureLineAdaptTransformAlgo.cpp
 point_set/QuadratureAdaptTransformAlgoFactory.cpp
)
