set(MPI_Fortran_COMPILER ${PDEKIT_MPI_Fortran_COMPILER})
set(MPI_C_COMPILER ${PDEKIT_MPI_C_COMPILER})
set(MPI_CXX_COMPILER ${PDEKIT_MPI_CXX_COMPILER})

find_package( MPI REQUIRED )

if( MPI_CXX_FOUND )
  include_directories( ${MPI_CXX_INCLUDE_PATH} )
  list(APPEND PDEKIT_MPI_LIBS ${MPI_CXX_LIBRARIES} )

  set( PDEKIT_HAVE_MPI 1 )

endif( MPI_CXX_FOUND )
