list(APPEND PDEKIT_Solver_RDM_HEADERS
RDMethod.hpp
RDSolver.hpp
DRDMethodLFImpl.hpp
DRDMethodExplicit.hpp
DRDMethodImplicit.hpp
ImplicitDRDFullJacobianImpl.hpp
KeyGenerators.hpp
PGRDMethodExplicit.hpp
PGRDMethodImplicit.hpp
ImplicitPGRDFullJacobianImpl.hpp
assembly/RDMCellWorker.hpp
assembly/PGRDMExplicitCellWorker.hpp
assembly/PGRDMExplicitFacetWorker.hpp
assembly/PGRDMExplicitFacetWorkerTrDiff.hpp
assembly/PGRDMImplicitCellAssemblyWorker.hpp
assembly/PGRDMFinDiffCellAssemblyWorker.hpp
assembly/PGRDMPicardJacCellAssemblyWorker.hpp
assembly/PGRDMFullJacFacetAssemblyWorker.hpp
blending_coeff/RDBlendingCoeff.hpp
blending_coeff/BlendingCoeffImplBase.hpp
blending_coeff/LFBlendingCoeffImpl.hpp
blending_coeff/WongJansenBlendingCoeffImpl.hpp
blending_coeff/ArtViscIndicatorCoeffImpl.hpp
blending_coeff/BonanniBlendingCoeffImpl.hpp
RDMethodConstData.hpp
RDMethodScratchData.hpp
RDTimeUpdate.hpp
cellsplitters/CellSchemeSelector.hpp
cellsplitters/CellSplitters.hpp
cellsplitters/PGB.hpp
cellsplitters/PGLDA.hpp
cellsplitters/PGLF1.hpp
cellsplitters/PGN.hpp
cellsplitters/SUPG.hpp
cellsplitters/LF.hpp
cellsplitters/Galerkin.hpp
cellsplitters/LFResidualLimiter.hpp
facetsplitters/FacetSchemeSelector.hpp
facetsplitters/FacetSplitters.hpp
facetsplitters/FacetLDA.hpp
facetsplitters/FacetDG.hpp
facetsplitters/FacetLF.hpp
multigrid/PMultigridRDM.hpp
bc/RDMBCBase.hpp
bc/RDMBCManager.hpp
bc/StrongDirichletBC.hpp
bc/WeakBC.hpp
bc/RDMBCMetricData.hpp
bc/RDMBCProjectionData.hpp
bc/WeakDirichletBC.hpp
bc/WeakFarfield.hpp
bc/WeakSubInlet.hpp
bc/WeakSuperInlet.hpp
bc/WeakSubOutlet.hpp
bc/WeakSymmetry.hpp
bc/WeakWall.hpp
)

list(APPEND PDEKIT_Solver_RDM_SOURCES
RDTimeUpdate.cpp
)
