list(APPEND PDEKIT_Common_HEADERS
PDEKit.hpp
AbstractFactory.hpp
ArrayShape.hpp
ArrayView.hpp
BlockArray.hpp
BlockMultiArray.hpp
Component.hpp
Constants.hpp
DataMapIterator.hpp
DataMap.hpp
DataMapImpl.hpp
FactoryT.hpp
FactoryPool.hpp
Flyweight.hpp
FWInstanceContainer.hpp
Hash.hpp
TaggedBool.hpp
TaggedInt.hpp
IteratorRange.hpp
IOStreamUtils.hpp
Core.hpp
Meta.hpp
TupleMeta.hpp
OptionMap.hpp
Provider.hpp
PtrHandle.hpp
SharedPointer.hpp
Singleton.hpp
StringUtils.hpp
CRTPSingleton.hpp
Range1D.hpp
SmallIntegerPack.hpp
TupleOf.hpp
URI.hpp
VectorUtils.hpp
)

list(APPEND PDEKIT_Common_SOURCES
AbstractFactory.cpp
Component.cpp
Constants.cpp
Core.cpp
Hash.cpp
FactoryPool.cpp
OptionMap.cpp
StringUtils.cpp
URI.cpp
)
